/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkforceRouteImport } from './routes/workforce'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'

const WorkforceRoute = WorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/payroll': typeof PayrollRoute
  '/planning': typeof PlanningRoute
  '/setup': typeof SetupRoute
  '/workflow': typeof WorkflowRoute
  '/workforce': typeof WorkforceRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/payroll': typeof PayrollRoute
  '/planning': typeof PlanningRoute
  '/setup': typeof SetupRoute
  '/workflow': typeof WorkflowRoute
  '/workforce': typeof WorkforceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/payroll': typeof PayrollRoute
  '/planning': typeof PlanningRoute
  '/setup': typeof SetupRoute
  '/workflow': typeof WorkflowRoute
  '/workforce': typeof WorkforceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/dashboard'
    | '/insights'
    | '/payroll'
    | '/planning'
    | '/setup'
    | '/workflow'
    | '/workforce'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/dashboard'
    | '/insights'
    | '/payroll'
    | '/planning'
    | '/setup'
    | '/workflow'
    | '/workforce'
  id:
    | '__root__'
    | '/about'
    | '/dashboard'
    | '/insights'
    | '/payroll'
    | '/planning'
    | '/setup'
    | '/workflow'
    | '/workforce'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  InsightsRoute: typeof InsightsRoute
  PayrollRoute: typeof PayrollRoute
  PlanningRoute: typeof PlanningRoute
  SetupRoute: typeof SetupRoute
  WorkflowRoute: typeof WorkflowRoute
  WorkforceRoute: typeof WorkforceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workforce': {
      id: '/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof WorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  InsightsRoute: InsightsRoute,
  PayrollRoute: PayrollRoute,
  PlanningRoute: PlanningRoute,
  SetupRoute: SetupRoute,
  WorkflowRoute: WorkflowRoute,
  WorkforceRoute: WorkforceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
